dashboard:
  title: Neutron Dynamic Routing Failure Rates
  rows:
    - title: Description
      height: 100px
      panels:
        - title: Description
          content: |
            **This dashboard is managed by [Grafyaml](http://docs.openstack.org/infra/system-config/grafyaml.html).**

            If you would like to make changes to this dashboard, please see the grafana directory in [project-config](https://git.openstack.org/cgit/openstack-infra/project-config/tree/grafana/neutron-dynamic-routing.yaml).
          type: text
    - title: Graphs
      height: 320px
      panels:
        - title: Unit Test Failure Rates (Check queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-neutron-dynamic-routing-python27-ubuntu-xenial.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-neutron-dynamic-routing-python27-ubuntu-xenial.{SUCCESS,FAILURE})),'24hours'), 'gate-neutron-dynamic-routing-python27-ubuntu-xenial')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-neutron-dynamic-routing-python34.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-neutron-dynamic-routing-python34.{SUCCESS,FAILURE})),'24hours'), 'gate-neutron-dynamic-routing-python34')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-neutron-dynamic-routing-python35.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-neutron-dynamic-routing-python35.{SUCCESS,FAILURE})),'24hours'), 'gate-neutron-dynamic-routing-python35')
          type: graph
        - title: Unit Test Failure Rates (Gate queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-neutron-dynamic-routing-python27-ubuntu-xenial.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-neutron-dynamic-routing-python27-ubuntu-xenial.{SUCCESS,FAILURE})),'24hours'), 'gate-neutron-dynamic-routing-python27-ubuntu-xenial')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-neutron-dynamic-routing-python34.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-neutron-dynamic-routing-python34.{SUCCESS,FAILURE})),'24hours'), 'gate-neutron-dynamic-routing-python34')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-neutron-dynamic-routing-python35.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-neutron-dynamic-routing-python35.{SUCCESS,FAILURE})),'24hours'), 'gate-neutron-dynamic-routing-python35')
          type: graph
        - title: Periodic Job Failure Rates
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.periodic.job.neutron-dynamic-routing-py35-with-neutron-lib-master.FAILURE),sum(stats_counts.zuul.pipeline.periodic.job.periodic-neutron-dynamic-routing-py35-with-neutron-lib-master.{SUCCESS,FAILURE})),'24hours'), 'periodic-neutron-dynamic-routing-py35-with-neutron-lib-master')
          type: graph
        - title: Integrated Failure Rates (Gate queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-neutron-dynamic-routing-dsvm-tempest-api.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-neutron-dynamic-routing-dsvm-tempest-api.{SUCCESS,FAILURE})),'24hours'), 'gate-neutron-dynamic-routing-dsvm-tempest-api')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-neutron-dynamic-routing-dsvm-functional.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-neutron-dynamic-routing-dsvm-functional.{SUCCESS,FAILURE})),'24hours'), 'gate-neutron-dynamic-routing-dsvm-functional')
          type: graph
